<a href="https://colab.research.google.com/github/FuadhistyOyes/preprocessingdata/blob/main/preprocessingdata.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Langkah Awal sebslum kita menjalankan preprocessingdata, kita harus menginport library seperti di bawah ini:

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Setelah mengimpor library, langkah berikutnya adalah membaca data dari file CSV yang berisi nilai X dan Y.

In [3]:
dataset = pd.read_csv('data_penduduk_jatim.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

menjalankan printah untuk membaca nilai X

In [4]:
print(x)

[['Surabaya' 45.0 7500000.0]
 ['Malang' 29.0 4600000.0]
 ['Kediri' 33.0 nan]
 ['Surabaya' nan 6200000.0]
 ['Jember' 40.0 7100000.0]
 ['Malang' 38.0 nan]
 ['Kediri' 28.0 5300000.0]
 ['Surabaya' 50.0 8000000.0]
 ['Jember' 42.0 8500000.0]
 ['Malang' nan 6700000.0]]


menjalankan printah untuk membaca nilai Y

In [5]:
print(y)

['Ya' 'Tidak' 'Ya' 'Tidak' 'Ya' 'Tidak' 'Ya' 'Tidak' 'Ya' 'Tidak']


Jika terdapat nilai yang hilang dalam dataset, kita akan mengisinya dengan nilai rata-rata (mean) dari masing-masing kolom.

In [6]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

Ketika kita menjalankan kode print(X), program akan menampilkan data X setelah proses pengisian nilai yang hilang dengan rata-rata (mean). Ini berguna untuk memastikan bahwa semua nilai yang hilang telah terisi dengan benar dan dataset siap digunakan untuk analisis lebih lanjut.

In [7]:
print(x)

[['Surabaya' 45.0 7500000.0]
 ['Malang' 29.0 4600000.0]
 ['Kediri' 33.0 6737500.0]
 ['Surabaya' 38.125 6200000.0]
 ['Jember' 40.0 7100000.0]
 ['Malang' 38.0 6737500.0]
 ['Kediri' 28.0 5300000.0]
 ['Surabaya' 50.0 8000000.0]
 ['Jember' 42.0 8500000.0]
 ['Malang' 38.125 6700000.0]]


Kita akan mengubah data kategorikal menjadi bentuk numerik menggunakan One-Hot Encoding. Metode ini akan mengonversi setiap kategori unik dalam kolom menjadi vektor biner, sehingga data lebih mudah diproses oleh algoritma machine learning.

In [9]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

Saat kita menjalankan print(X), program akan menampilkan data X setelah dikonversi menggunakan One-Hot Encoding. Ini memungkinkan kita untuk melihat bagaimana data kategorikal telah diubah menjadi bentuk numerik dengan representasi vektor biner.

In [10]:
print(x)

[[0.0 0.0 0.0 1.0 45.0 7500000.0]
 [0.0 0.0 1.0 0.0 29.0 4600000.0]
 [0.0 1.0 0.0 0.0 33.0 6737500.0]
 [0.0 0.0 0.0 1.0 38.125 6200000.0]
 [1.0 0.0 0.0 0.0 40.0 7100000.0]
 [0.0 0.0 1.0 0.0 38.0 6737500.0]
 [0.0 1.0 0.0 0.0 28.0 5300000.0]
 [0.0 0.0 0.0 1.0 50.0 8000000.0]
 [1.0 0.0 0.0 0.0 42.0 8500000.0]
 [0.0 0.0 1.0 0.0 38.125 6700000.0]]


Kita akan mengonversi data kategorikal menjadi bentuk numerik menggunakan Label Encoding. Metode ini menggantikan setiap kategori unik dengan angka tertentu, sehingga data dapat digunakan dalam pemrosesan machine learning.

In [14]:
from sklearn.preprocessing import LabelEncoder
le= LabelEncoder()
y=le.fit_transform(y)

Saat kita menjalankan `print(y)`, program akan menampilkan data y setelah dikonversi menggunakan Label Encoding. Ini memungkinkan kita melihat bagaimana setiap kategori telah digantikan dengan nilai numerik.


In [15]:
print(y)

[1 0 1 0 1 0 1 0 1 0]


Kita akan membagi dataset menjadi data latih (training) dan data uji (testing) agar model machine learning dapat belajar dari data latih dan dievaluasi menggunakan data uji.

In [16]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

Saat kita menjalankan print(X_train), program akan menampilkan data latih (training) setelah proses pembagian dataset. Data ini digunakan oleh model machine learning untuk belajar pola dari dataset.

In [17]:
print(x_train)

[[0.0 1.0 0.0 0.0 28.0 5300000.0]
 [1.0 0.0 0.0 0.0 40.0 7100000.0]
 [0.0 0.0 0.0 1.0 45.0 7500000.0]
 [0.0 0.0 0.0 1.0 38.125 6200000.0]
 [0.0 0.0 1.0 0.0 29.0 4600000.0]
 [0.0 0.0 0.0 1.0 50.0 8000000.0]
 [1.0 0.0 0.0 0.0 42.0 8500000.0]
 [0.0 0.0 1.0 0.0 38.0 6737500.0]]


Saat kita menjalankan print(X_test), program akan menampilkan data uji (testing) setelah proses pembagian dataset. Data ini digunakan untuk menguji kinerja model setelah dilatih.

In [18]:
print(x_test)

[[0.0 1.0 0.0 0.0 33.0 6737500.0]
 [0.0 0.0 1.0 0.0 38.125 6700000.0]]


Saat kita menjalankan print(y_train), program akan menampilkan data latih (training) untuk variabel target (y). Data ini digunakan oleh model machine learning untuk belajar dan menemukan pola dari dataset.

In [19]:
print(y_train)

[1 1 1 0 0 0 1 0]


Saat kita menjalankan print(y_test), program akan menampilkan data uji (testing) untuk variabel target (y). Data ini digunakan untuk mengukur seberapa baik model dapat memprediksi hasil berdasarkan data yang belum pernah dilihat sebelumnya.

In [20]:
print(y_test)

[1 0]


Kita akan menstandarisasi fitur numerik dalam dataset menggunakan StandardScaler dari sklearn.preprocessing. Metode ini mengubah data sehingga memiliki rata-rata 0 dan standar deviasi 1, sehingga model machine learning dapat bekerja lebih optimal.

In [21]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 4:] = sc.fit_transform(x_train[:, 4:])
x_test[:, 4:]= sc.transform(x_test[:, 4:])

Saat kita menjalankan `print(X_train)`, program akan menampilkan data latih (training) setelah proses standarisasi. Data ini telah diubah sehingga memiliki rata-rata 0 dan standar deviasi 1, membantu model machine learning bekerja lebih optimal.

In [22]:
print(x_train)

[[0.0 1.0 0.0 0.0 -1.5432185735845951 -1.1613389224359332]
 [1.0 0.0 0.0 0.0 0.17694378419910453 0.2881328420778209]
 [0.0 0.0 0.0 1.0 0.8936780999423127 0.610237678636433]
 [0.0 0.0 0.0 1.0 -0.09183158420459855 -0.43660304017905616]
 [0.0 0.0 1.0 0.0 -1.3998717104359535 -1.7250223864135041]
 [0.0 0.0 0.0 1.0 1.6104124156855208 1.0128687243346979]
 [1.0 0.0 0.0 0.0 0.4636375104963878 1.415499770032963]
 [0.0 0.0 1.0 0.0 -0.10974994209817876 -0.0037746660534212348]]
